---
title: 'EX1 Experiment for Google users'
author: 'Mint Metrics'
date: Knitted `r format(Sys.Date(),format = "%d %B %Y")`
header-includes:
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
mainfont: Roboto Light
---
```{r includes, include=FALSE, echo=FALSE, cache=FALSE, warning=FALSE}
# Optional: Path to Redshift/PostgreSQL connection (must expose "con" connection variable in this namespace)
for (lib in c("reports","plots","tables","queries_snowplow_redshift","experiment_sizing")) {
  source(paste0("./mojito-functions/",lib,".R"))
}
```
```{r options, echo=FALSE, include=FALSE, message=FALSE, warning=FALSE}
wave_params <- list(
  client_id = "mintmetrics",
  wave_id = "ex1",
  start_date = "2019-05-15 09:19:45",
  stop_date = "2019-06-05 14:29:00",
  time_grain = "days",
  subject = "usercookie",
  recipes = c("Control", "Treatment")
)
```

## Details

**Hypotheses:  ** The treatment will increase transactions.

**Started:     ** `r wave_params$start_date`

**Ended:       ** `r mojitoReportDates(wave_params)`

## Summary

 * TBA

```{r, echo=FALSE, message=FALSE, warning=FALSE, results='asis', fig.height=3, fig.width=10, fig.align='center'}
goalList <- list(
  list(
    title = "Transactions",
    goal = "purchase",
    operand = "="
  ),
  list(
    title = "Page views",
    goal = "page_view %",
    operand = "like"
  )
)
goalList <- mojitoFullKnit(wave_params, goal_list = goalList)
```

# Test diagnostics

```{r, echo=FALSE, message=FALSE, warning=FALSE, results='asis', fig.height=3, fig.width=10, fig.align='center'}
mojitoDiagnostics(wave_params, lapply(goalList, "[")[[1]]$result)
```
